# Generated by Django 3.0.3 on 2021-01-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('dishes', models.CharField(max_length=300)),
                ('fav_dish', models.CharField(max_length=30)),
                ('rating', models.IntegerField(max_length=5)),
                ('visited', models.BooleanField()),
            ],
        ),
    ]
