# Generated by Django 4.1 on 2022-08-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210125_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopedetails',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
